export type ProcedureCategory = "General Orthopaedics" | "Pediatric" | "Arthroscopy" | "Arthroplasty" | "Spine" | "Oncology" | "Hand";

export const DISCHARGE_PROCEDURE_OPTIONS: Record<ProcedureCategory, string[]> = {
    "General Orthopaedics": [
        "History taking & Physical examination",
        "Ordering investigations & Interpreting results",
        "Deciding and implementing appropriate treatment",
        "Post-operative management & monitoring",
        "Debridement and Suture Techniques",
        "Intraarticular/ Intralesional Injections",
        "Presentation skills long cases",
        "Presentation skills short cases",
        "Use of Orthopaedics Instruments/Orthosis",
        "Skeletal Traction / Skin Traction",
        "Application of Plaster of Paris Cast",
        "Closed treatment (Manipulations)",
        "Closed treatment (Dislocations)",
        "Skin Grafting",
        "Biopsy",
        "External fixation of fractures of lower limb",
        "External fixation of fractures of upper limb",
        "Bone grafting",
        "Plating of Long Bones",
        "Intramedullary nailing of long bones",
        "Fixation of trochanteric and neck of femur fractures",
        "Fixation of fracture around knee joint",
        "Complex trauma / Poly trauma",
        "Osteotomies",
        "Arthrodesis",
        "Amputation",
        "Tendon repair",
        "Nerve repair",
        "Bone tumor surgery"
    ],
    "Pediatric": [
        "Pediatric: History Taking & Physical Examination",
        "Pediatric: Ordering Investigations & Interpreting Results",
        "Pediatric: Deciding and Implementing Appropriate Treatment",
        "Pediatric: Post-Operative Management and Monitoring",
        "Pediatric: Presentation Skills: Short Case",
        "Pediatric: Presentation Skills: Long Case",
        "Pediatric: Use of Relevant Surgical Instruments",
        "Pediatric: Pediatric Elbow Trauma Surgery",
        "Pediatric: Pediatric Corrective Osteotomies",
        "Pediatric: Miscellaneous Surgery (CTEV/DDH/POLIO/CP)",
        "Pediatric: Surgery for Osteomyelitis"
    ],
    "Arthroscopy": [
        "Arthroscopy: History Taking & Physical Examination",
        "Arthroscopy: Ordering Investigations & Interpreting Results",
        "Arthroscopy: Deciding and Implementing Appropriate Treatment",
        "Arthroscopy: Post-Operative Management and Monitoring",
        "Arthroscopy: Presentation Skills: Short Case",
        "Arthroscopy: Presentation Skills: Long Case",
        "Arthroscopy: Use of Relevant Surgical Instruments",
        "Arthroscopy: Diagnostic Arthroscopy",
        "Arthroscopy: ACL/PCL reconstruction",
        "Arthroscopy: Meniscal Surgery",
        "Arthroscopy: Shoulder Arthroscopy"
    ],
    "Arthroplasty": [
        "Arthroplasty: History Taking & Physical Examination",
        "Arthroplasty: Ordering Investigations & Interpreting Results",
        "Arthroplasty: Deciding and Implementing Appropriate Treatment",
        "Arthroplasty: Post-Operative Management and Monitoring",
        "Arthroplasty: Presentation Skills: Short Case",
        "Arthroplasty: Presentation Skills: Long Case",
        "Arthroplasty: Use of Relevant Surgical Instruments",
        "Arthroplasty: Hemiarthroplasty of Hip",
        "Arthroplasty: Primary Total Hip Replacement",
        "Arthroplasty: Primary Total Knee Replacement"
    ],
    "Spine": [
        "Spine: History Taking & Physical Examination",
        "Spine: Ordering Investigations & Interpreting Results",
        "Spine: Deciding and Implementing Appropriate Treatment",
        "Spine: Post-Operative Management and Monitoring",
        "Spine: Presentation Skills: Short Case",
        "Spine: Presentation Skills: Long Case",
        "Spine: Use of Relevant Surgical Instruments",
        "Spine: Spinal Trauma Fixation",
        "Spine: Procedures for Degenerative Spine (Discectomy/Laminectomy)",
        "Spine: Procedures for Spine Infections (Pyogenic, TB)"
    ],
    "Oncology": [
        "Oncology: History Taking & Physical Examination",
        "Oncology: Ordering Investigations & Interpreting Results",
        "Oncology: Deciding and Implementing Appropriate Treatment",
        "Oncology: Post-Operative Management and Monitoring",
        "Oncology: Presentation Skills: Short Case",
        "Oncology: Presentation Skills: Long Case",
        "Oncology: Use of Relevant Surgical Instruments",
        "Oncology: Biopsy (Open/ Core/ Needle)",
        "Oncology: Treatment of Soft Tissue Tumors",
        "Oncology: Treatment of Bone Tumors"
    ],
    "Hand": [
        "Hand: History Taking & Physical Examination",
        "Hand: Ordering Investigations & Interpreting Results",
        "Hand: Deciding and Implementing Appropriate Treatment",
        "Hand: Post-Operative Management and Monitoring",
        "Hand: Presentation Skills: Short Case",
        "Hand: Presentation Skills: Long Case",
        "Hand: Use of Relevant Surgical Instruments",
        "Hand: Hand / Wrist Fracture Fixation",
        "Hand: Carpal Tunnel Release",
        "Hand: Tendon Repair / Tendon Transfer",
        "Hand: Nerve Repair"
    ]
};
